name: vpnclient_engine_flutter
description: "VPN Client Engine Flutter plugin"
version: 0.0.1
homepage: "https://vpnclient.click"

environment:
  sdk: ^3.7.2
  flutter: 3.29.3

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2
  cupertino_icons: ^1.0.8
  dart_ping: ^9.0.1
  http: ^1.3.0
  flutter_v2ray: ^1.0.10
  rxdart: ^0.28.0
  #vpnclient_engine_android:
    #git:
      #url: https://github.com/VPNclient/VPNclient-engine.git
      #ref: main
      #path: android/
  vpnclient_engine_ios:
    path: ../VPNclient-engine-ios
  vpnclient_engine_macos:
    path: ../VPNclient-engine-ios
  #vpnclient_engine_windows:
    #git:
      #url: https://github.com/VPNclient/VPNclient-engine.git
      #ref: main
      #path: windows/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: click.vpnclient.engine.flutter
        pluginClass: VpnclientEngineFlutterPlugin
      ios:
        pluginClass: VpnclientEngineFlutterPlugin
      linux:
        pluginClass: VpnclientEngineFlutterPlugin
      macos:
        pluginClass: VpnclientEngineFlutterPlugin
      windows:
        pluginClass: VpnclientEngineFlutterPluginCApi
      web:
        pluginClass: VpnclientEngineFlutterWeb
        fileName: vpnclient_engine_flutter_web.dart
