project '../../VPNclient-engine-ios/cntrlr.xcodeproj'
platform :ios, '12.0'
use_frameworks!


target 'VPNclientEngineFlutter' do
  use_frameworks!
  pod 'VPNclientEngine', :path => '../../VPNclient-engine-ios'
  pod 'VPNclientTunnel', :path => '../../VPNclient-engine-ios'
end
